apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <NAMESPACE>
  name: frontend-deployment
  labels:
    app: synple-gui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synple-gui
  template:
    metadata:
      labels:
        app: synple-gui
    spec:
      dnsPolicy: Default
      containers:
        - name: synple-frontend
          image: virtuatable/modusynth-frontend:<VERSION>
          args:
            - web
          ports:
            - containerPort: 3000
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: api
                  key: url
            - name: PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: frontend-credentials
                  key: public-key
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: frontend-credentials
                  key: private-key
            - name: NUXT_APP_BASE_URL
              value: <PUBLIC_PATH>
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 500m
              memory: 128Mi