version: 2.1

parameters:
  env:
    type: string
    default: dev


jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    description: Deploys an application given its Github repository and the parameters needed for its Kubernetes deployment
    parameters:
      env:
        type: string
        default: dev
    steps:
      - checkout
      - run:
          name: Configuration storage
          command: cat ./environments/<< parameters.env >>.env >> $BASH_ENV
      - run:
          name: configuration traces
          command: echo $KUBE_NS

commands:


workflows:
  deploy-stack:
    jobs:
      - deploy:
          env: dev