version: 2.1

orbs:
  kube: circleci/kubernetes@1.3.0

parameters:
  env:
    type: string
    default: dev


jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    description: Deploys an application given its Github repository and the parameters needed for its Kubernetes deployment
    parameters:
      env:
        type: string
        default: dev
      repository:
        type: string
        default: API_REPOSITORY
    steps:
      - checkout
      - run:
          name: Configuration storage
          command: cat ./environments/<< parameters.env >>/.env >> $BASH_ENV
      - kube/install-kubectl
      - kube/install-kubeconfig
      - setup_remote_docker:
          version: 20.10.14
      - run:
          name: Authenticate on Docker HUB from environment variable
          command: echo ${DOCKER_PASSWORD} | docker login --username ${DOCKER_USERNAME} --password-stdin
      - fetch_version:
          repository: << parameters.repository >>
      - deploy_stack

commands:
  fetch_version:
    parameters:
      repository:
        type: string
        default: API_REPOSITORY
    steps:
      - run:
          name: Tags storage
          command: curl https://hub.docker.com/v2/repositories/${DOCKER_USERNAME}/${<< parameters.repository >>}/tags -o tags.json
      - run:
          name: Last version traces
          command: export LAST_VERSION=$(cat tags.json | jq .results | jq .[0] | jq .name) && echo "export VERSION=${LAST_VERSION}" >> $BASH_ENV
  deploy_stack:
    steps:
      - run:
          name: Version tracing
          command: cat $BASH_ENV

workflows:
  deploy-stack:
    jobs:
      - deploy:
          env: << pipeline.parameters.env >>
          repository: GUI_REPOSITORY
      - deploy:
          env: << pipeline.parameters.env >>
          repository: API_REPOSITORY