version: 2.1

parameters:
  deploy_app:
    type: boolean
    default: false

jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    description: Deploys an application given its Github repository and the parameters needed for its Kubernetes deployment
    parameters:
      deploy_app:
        type: boolean
        default: false
    steps:
      - when:
          condition: << parameters.deploy_app >>
          steps:
            - run: echo "Oui déploiement"

workflows:
  deploy-stack:
    jobs:
      - deploy:
          deploy_app: << pipeline.parameters.deploy_app >>