version: 2.1

parameters:
  # TRUE to deploy the frontend in the pipeline, FALSE otherwise.
  frontend:
    type: boolean
    default: false
  # TRUE to deploy the API in the pipeline, FALSE otherwise.
  api:
    type: boolean
    default: false


jobs:
  deploy:
    docker:
      - image: cimg/base:stable
    description: Deploys an application given its Github repository and the parameters needed for its Kubernetes deployment
    parameters:
      frontend:
        type: boolean
        default: false
      api:
        type: boolean
        default: false
    steps:
      - when:
          condition: << parameters.frontend >>
          steps:
            - run: echo "Oui déploiement frontend"
      - unless:
          condition: << parameters.frontend >>
          steps:
            - run: echo "Non déploiement frontend"
      - when:
          condition: << parameters.api >>
          steps:
            - run: echo "Oui déploiement API"
      - unless:
          condition: << parameters.api >>
          steps:
            - run: echo "Non déploiement API"

commands:


workflows:
  deploy-stack:
    jobs:
      - deploy:
          api: << pipeline.parameters.api >>
          frontend: << pipeline.parameters.frontend >>