apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <NAMESPACE>
  name: api-deployment
  labels:
    app: modusynth-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modusynth-api
  template:
    metadata:
      labels:
        app: modusynth-api
    spec:
      dnsPolicy: Default
      containers:
        - name: modusynth-api
          image: virtuatable/modusynth-api:<VERSION>
          args:
            - web
          ports:
            - containerPort: 3000
          env:
            - name: RACK_ENV
              value: production
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: api
                  key: database-uri