apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: <NAMESPACE>
  name: api-deployment
  labels:
    app: synple-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: synple-api
  template:
    metadata:
      labels:
        app: synple-api
    spec:
      dnsPolicy: Default
      containers:
        - name: synple-api
          image: virtuatable/modusynth-api:<VERSION>
          args:
            - web
          ports:
            - containerPort: 3000
          env:
            - name: RACK_ENV
              value: production
            - name: MONGODB_URL
              valueFrom:
                secretKeyRef:
                  name: api
                  key: database-uri
            - name: KUBECONFIG
              value: "/etc/kubeconfig"
            - name: KUBE_NS
              value: <NAMESPACE>
          volumeMounts:
            name: kubeconfig
            mountPath: /etc
            readOnly: true
      volumes:
        - name: kubeconfig
          configMap:
            name: kube
            items:
              key: config
              path: 'kubeconfig.yml'